---

namespace: community

name: sap_operations

version: 1.0.0

readme: README.md

authors:
  - IBM Lab for SAP Solutions
  - IBM Cloud for SAP
  - IBM Consulting for SAP
  - Ondra Machacek <omachace@redhat.com>
  - Kirill Satarin (@kksat)

description: Collection of Ansible Modules and Ansible Roles for SAP system operations

license:
  - Apache-2.0
  - GPL-2.0-or-later

license_file: 'LICENSE'

tags:
  - linux
  - sap

dependencies:
  community.sap_libs: '*'

repository: http://github.com/sap-linuxlab/community.sap_operations

documentation: https://github.com/sap-linuxlab/sap-linuxlab.github.io/blob/master/README.md

homepage: https://sap-linuxlab.github.io

issues: https://github.com/sap-linuxlab/community.sap_operations/issues

build_ignore: ['tests', 'internal']
