---
dependency:
  name: shell
  command: |
    ansible-galaxy install -r $MOLECULE_SCENARIO_DIRECTORY/requirements.yml
    pip install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt

driver:
  name: molecule-driver-azure

platforms:
  - name: prepare8
    resourcegroup_name: molecule
    vm_size: Standard_B1s
    marketplace_image:
      offer: rhel-sap-ha
      publisher: redhat
      sku: "8_6"
      version: latest

scenario:
  create_sequence:
    - create
  converge_sequence:
    - converge
  test_sequence:
    - dependency
    - destroy
    - create
    - converge
    - idempotence
    - destroy
  destroy_sequence:
    - destroy

provisioner:
  name: ansible
  playbooks:
    create: ../default/create.yml
    prepare: ""
    converge: ../default/converge.yml
    side-effect: ../default/side_effect.yml
    verify: ../default/verify.yml
    destroy: ../default/destroy.yml
verifier:
  name: ansible
