---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:

    - name: Include tested role
      include_role:
        name: "unpack"
        # tasks_from: prerequisites.yml
      vars:
        unpack_source:
          - /usr/sap/IMDB_CLIENT20_013_22-80002082.SAR
          - /usr/sap/SAPJVM8_90-80000202.SAR
          - /usr/sap/51055299.ZIP
          - /usr/sap
          - /does/not/exists
        unpack_destination: /usr/sap/dest
