---
dependency:
  name: shell
  command: |
    ansible-galaxy install -r $MOLECULE_SCENARIO_DIRECTORY/requirements.yml
    pip install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt

driver:
  name: molecule-driver-azure

platforms:
  - name: prepare9
    resourcegroup_name: molecule
    vm_size: Standard_B1s
    marketplace_image:
      publisher: redhat
      offer: "rhel_test_offers"
      sku: "9_0_sap_apps"
      version: latest
    plan:
      name: "9_0_sap_apps"
      product: "rhel_test_offers"
      # promotion_code: ""
      publisher: "redhat"

scenario:
  create_sequence:
    - create
  converge_sequence:
    - converge
  test_sequence:
    - dependency
    - destroy
    - create
    - converge
    - idempotence
    - destroy
  destroy_sequence:
    - destroy

provisioner:
  name: ansible
  playbooks:
    create: ../default/create.yml
    prepare: ""
    converge: ../default/converge.yml
    side-effect: ../default/side_effect.yml
    verify: ""
    destroy: ../default/destroy.yml
verifier:
  name: ansible
