---
dependency:
  name: shell
  command: |
    ansible-galaxy install -r $MOLECULE_SCENARIO_DIRECTORY/requirements.yml
    pip install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt

driver:
  name: molecule-driver-azure

platforms:
  - name: prepare7
    resourcegroup_name: molecule
    vm_size: Standard_B1s
    marketplace_image:
      offer: "rhel-sap-apps"
      publisher: redhat
      sku: "7_9"
      version: "latest"

scenario:
  create_sequence:
    - create
  converge_sequence:
    - converge
  test_sequence:
    - dependency
    - destroy
    - create
    - converge
    - idempotence
    - destroy
  destroy_sequence:
    - destroy

provisioner:
  name: ansible
  playbooks:
    create: create.yml
    prepare: ""
    converge: converge.yml
    side-effect: side_effect.yml
    verify: ../default/verify.yml
    destroy: destroy.yml
verifier:
  name: ansible
