---
- name: Halt
  hosts: localhost
  connection: local
  gather_facts: false
  # no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Print
      ansible.builtin.debug:
        msg: "Hello World"
      no_log: false
